{
 "title": "Forninho da Bela-Gil",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{ method }} - {{ handler }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Success Rate (Not 5xx)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status!~\"5.*\"}[1m])) / sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Requests with some recommendation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(sum_over_time(recommendations_per_request_total{amount!=\"0\"}[$__range]))\n    / on() group_left()\n  sum(sum_over_time(recommendations_per_request_total[$__range]))\n)"
    }
   ]
  },
  {
   "title": "Average step time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "processing_time_seconds_sum / processing_time_seconds_count",
     "legendFormat": "{{ step }}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_highr_seconds_bucket[$__range])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_highr_seconds_bucket[$__range])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_highr_seconds_bucket[$__range])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Recommendations per request",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(sum_over_time(recommendations_per_request_total[$__range])) by (amount)\n    / on() group_left()\n  sum(sum_over_time(recommendations_per_request_total[$__range]))\n)",
     "legendFormat": "{{ amount }}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "mem" }
   ]
  }
 ]
}