version: "3.8"

services:
  api:
    build: .
    env_file:
      - .env
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SESSION_TOKEN: '${AWS_SESSION_TOKEN}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    volumes:
      - ".:/usr/src/api"

  etl:
    build: .
    env_file:
      - .env
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SESSION_TOKEN: '${AWS_SESSION_TOKEN}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    volumes:
      - ".:/usr/src/etl"

  redis:
    image: redis:6.2.6
    hostname: redis

networks:
  default:
    name: mlflow
    external: true
